# Generated by Django 3.2.4 on 2021-07-01 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cliente.tipocliente'),
        ),
    ]
